import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { JetBrains_Mono, Space_Grotesk } from "next/font/google";
import "./globals.css";

const bodyFont = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-body",
});

const headerFont = Space_Grotesk({
  variable: "--font-header",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        headerFont.variable,
        bodyFont.variable,
        "font-mono"
      )}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
